# Generated by Django 5.0.3 on 2024-04-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bg_imgg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_imgg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified_account',
        ),
    ]
