# Generated by Django 5.0.3 on 2024-05-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_retweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='retweet',
            new_name='original_tweet',
        ),
    ]
