# Generated by Django 5.0.3 on 2024-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_rename_retweet_tweet_original_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
